{% set name = "astroquery" %}
{% set version = "0.4.7" %}
{% set sha256 = "047fbacb0a4faec4cdb62675e919c244c1c35e661044fcbb6c9a933331747ec9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  # Note: pip-based install fails due to wanting to download astropy-helpers
  script: python setup.py install --offline --no-git --single-version-externally-managed --record=files.txt
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools

  run:
    - astropy-base >=4.2.1
    - beautifulsoup4 >=4.8
    - html5lib >=0.999
    - keyring >=15.0
    - python >={{ python_min }}
    - requests >=2.19
    - pyvo >=1.1
    - numpy >=1.18.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - astroquery

about:
  home: http://www.astropy.org/astroquery/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Functions and classes to access online astronomical data resources.
  dev_url: https://github.com/astropy/astroquery

extra:
  recipe-maintainers:
    - astrofrog
    - bsipocz
    - Cadair
    - guillochon
    - mwcraig
    - pllim
    - pkgw
