{% set name = "astroquery" %}
{% set version = "0.4.9" %}
{% set sha256 = "3de22683e43ea3d11e0a40b9a1cd3835cb4561182b2fe1ae14a69a4a5d072408" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # Note: pip-based install fails due to wanting to download astropy-helpers
  script: python setup.py install --offline --no-git --single-version-externally-managed --record=files.txt
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools

  run:
    - astropy-base >=5.0
    - beautifulsoup4 >=4.8
    - html5lib >=0.999
    - keyring >=15.0
    - python >={{ python_min }}
    - requests >=2.19
    - pyvo >=1.5
    - numpy >=1.20.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - astroquery

about:
  home: http://www.astropy.org/astroquery/
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Functions and classes to access online astronomical data resources.
  dev_url: https://github.com/astropy/astroquery

extra:
  recipe-maintainers:
    - astrofrog
    - bsipocz
    - Cadair
    - guillochon
    - mwcraig
    - pllim
    - pkgw
