{% set name = "astroquery" %}
{% set version = "0.3.8" %}
{% set md5 = "99d863bfd8c7332e3871e10e1048194c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - astropy
    - beautifulsoup4
    - html5lib
    - keyring
    - python
    - requests
    - setuptools

  run:
    - astropy
    - beautifulsoup4
    - html5lib
    - keyring
    - python
    - requests

test:
  imports:
    - astroquery

about:
  home: http://www.astropy.org/astroquery/
  license: BSD 3-clause
  license_file: LICENSE.rst
  summary: 'Functions and classes to access online astronomical data resources.'
  dev_url: https://github.com/astropy/astroquery

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - bsipocz
    - Cadair
    - guillochon
    - mwcraig
    - pllim
    - pkgw
