appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iYJiHYpsiDYsoVGjkFAYFfidROufsdO4ScBeo4v+dIpIo0KH2gc2KhYa+d7O7JMPOw5dHDg2uZpG7p3FECNmo5M8qT/0ayIjjNghwxUD6oWR09jssiTtW+D+8ViY8MkmeqfldY0hhE5u9mDBtgwCN27pfxVqJ39cjxD+gwnpvekURbEvRH4Ej7Y+L7oBPY2yXqRYsh/R8q9bfjyTvLser3WUNKDaQnbLtdpf9zVQVZ163WSNBauJvo2ig3LvcfiTWGCCAJBOo/LUo5WAt3ReNplKIOL6eSAD+RonNFv5fnsX3Wwa7zbhAMtwgS+ojfxvKPnE3qCUX0r8D7Vp/1hz0c8QhsB4ujLXmM8jduSssflMBpGhEGluE1X7atG676w1tRZXwu4cvDAHiUxWAQsZ8NrG+L2s+wyxfgtZ4Zgeh8ikXCKn+5PFh+oDuApKMQIEs0PJlGOEf/K7/ywiFe6rm5EtmUMXOOSSK7b9Y4r01yFt6flB2Dp+/xU84306p4puJbGSFtEQqpp7y6BIjFwC8TzO31kGrTehBGu9KMJqf+jyc3+kkgBHvSoFPCJMwUz3mmoX/PXsOv8pHvlKG4yw8vRQnqufCFPHz5CAjpG6vFmzUkURJlesX5UHx+IJ+5T6gyuiePnpwQtpThCHRRsi5Nbrsh2mTDZaZzxmj87E5NY=}
